cnblog/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve

from blog import views
from cnblog import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login),
    path('get_validCode_img/', views.get_validCode_img),
    path('index/', views.index),
    # 根地址即显示主页内容
    re_path('^$', views.index),
    path('register/', views.register),
    path('logout/', views.logout),



    # media 配置
    re_path(r"media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT})
]

blog/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser


class UserInfo(AbstractUser):
    """
    用户信息
    """
    nid = models.AutoField(primary_key=True)
    telephone = models.CharField(max_length=11, null=True, unique=True)
    avatar = models.FileField(upload_to='avatars/', default="avatars/default.png")
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    blog = models.OneToOneField(to='Blog', to_field='nid', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.username


class Blog(models.Model):
    """
    博客信息
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题', max_length=64)
    site_name = models.CharField(verbose_name='站点名称', max_length=64)
    theme = models.CharField(verbose_name='博客主题', max_length=32)

    def __str__(self):
        return self.title


class Category(models.Model):
    """
    博主个人文章分类表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid', on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid', on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Article(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name='文章标题')
    desc = models.CharField(max_length=255, verbose_name='文章描述')
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    content = models.TextField()

    comment_count = models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)

    user = models.ForeignKey(verbose_name='作者', to='UserInfo', to_field='nid', on_delete=models.CASCADE)
    category = models.ForeignKey(to='Category', to_field='nid', null=True, on_delete=models.CASCADE)
    tags = models.ManyToManyField(
        to="Tag",
        through='Article2Tag',
        through_fields=('article', 'tag'),
    )

    def __str__(self):
        return self.title


class Article2Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='文章', to="Article", to_field='nid', on_delete=models.CASCADE)
    tag = models.ForeignKey(verbose_name='标签', to="Tag", to_field='nid', on_delete=models.CASCADE)

    class Meta:
        unique_together = [
            ('article', 'tag'),
        ]

    def __str__(self):
        v = self.article.title + "---" + self.tag.title
        return v


class ArticleUpDown(models.Model):
    """
    点赞表
    """
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey('UserInfo', null=True, on_delete=models.CASCADE)
    article = models.ForeignKey("Article", null=True, on_delete=models.CASCADE)
    is_up = models.BooleanField(default=True)

    class Meta:
        unique_together = [
            ('article', 'user'),
        ]


class Comment(models.Model):
    """
    评论表
    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='nid', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid', on_delete=models.CASCADE)
    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    parent_comment = models.ForeignKey('self', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

blog/views.py
# _*_coding: utf-8_*_
#
# @author: kyle
# @date: 2021/12/5 17:08

from django.contrib import auth
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect

from blog import models
from blog.Myforms import UserForm
from blog.models import UserInfo
from blog.utils import validCode


def login(request):
    if request.method == "POST":
        response = {"user": None, "msg": None}

        user = request.POST.get("user")
        pwd = request.POST.get("pwd")

        valid_code = request.POST.get("valid_code")
        valid_code_str = request.session.get("valid_code_str")
        if valid_code.upper() == valid_code_str.upper():
            user = auth.authenticate(username=user, password=pwd)
            if user:
                auth.login(request, user)  # request.user == 当前登陆对象
                response["user"] = user.username
            else:
                # alert("username or password error!")
                response["msg"] = "user or password error!"
        else:
            response["msg"] = "valid code error!"
        return JsonResponse(response)
    return render(request, "login.html")


def get_validCode_img(request):
    """
    基于PIL模块动态生成响应状态码图片
    :param request:
    :return:
    """
    img_data = validCode.get_valid_code_img(request)
    return HttpResponse(img_data)


def index(request):
    article_list = models.Article.objects.all()
    return render(request, "index.html", {"article_list": article_list})


def register(request):
    # 提交检验
    if request.is_ajax():
        # print(request.POST)
        form = UserForm(request.POST)

        response = {"user": None, "msg": None}
        if form.is_valid():
            response["user"] = form.cleaned_data.get("user")

            # 生成一条用户记录
            user = form.cleaned_data.get("user")
            print("user:", user)
            pwd = form.cleaned_data.get("pwd")
            email = form.cleaned_data.get("email")

            avatar_obj = request.FILES.get("avatar")
            extra = {}
            if avatar_obj:
                extra["avatar"] = avatar_obj
                # user_obj = UserInfo.objects.create_user(username=user, password=pwd, email=email, avatar=avatar_obj)
                # user_obj = UserInfo.objects.create_user(username=user, password=pwd, email=email, **extra)
                UserInfo.objects.create_user(username=user, password=pwd, email=email, **extra)

        else:
            print(form.cleaned_data)
            print(form.errors)
            response["msg"] = form.errors
        return JsonResponse(response)

    form = UserForm()
    return render(request, "register.html", {"form": form})


def logout(request):
    # 等同于 request.session.flush()
    auth.logout(request)
    return redirect("/login/")

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/blog/bs/css/bootstrap.css">
    <script src="/static/js/jquery-3.2.1.min.js"></script>
    <script src="/static/blog/bs/js/bootstrap.js"></script>

    <style>
        #user_icon{
            font-size: 18px;
            margin-right: 10px;
            vertical-align: -3px;
        }

        .pub_info{
            margin-top: 10px;
        }

        .pub_info .glyphicon-comment{
            vertical-align: -1px;
        }
        .pub_info .glyphicon-thumbs-up{
            vertical-align: -1px;
        }
    </style>
</head>
<body>
<!--导航栏-->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">李大志的博客园</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">随笔 <span class="sr-only">(current)</span></a></li>
        <li><a href="#">博文</a></li>
        <li><a href="#">新闻</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">

        {% if request.user.is_authenticated %}
          <li><a href="#"><span id="user_icon" class="glyphicon glyphicon-user"></span>{{ request.user.username }}</a></li>
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#">修改密码</a></li>
                    <li><a href="/logout/">退出登陆</a></li>
                    <li><a href="#">更换头像</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                </ul>
            </li>
        {% else %}
          <li><a href="/login/">登录</a></li>
          <li><a href="/register/">注册</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!--页面中间部分，分左、中、右三部分-->
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
            <!-- 面板公告 -->
            <div class="panel panel-warning">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
            <!--面板信息-->
            <div class="panel panel-info">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
            <!--面板警示-->
            <div class="panel panel-danger">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>

        </div>
        <!--中间面板-->
        <div class="col-md-6">
            <div class="article_list">
                {% for article in article_list %}
                <div class="article-item">
                    <h5><a href="">{{ article.title }}</a></h5>
                    <div class="article-desc">
                        <!--头像渲染-->
                        <span class="media-left">
                            <a href=""><img width="46" height="46" src="media/{{ article.user.avatar }}" alt=""></a>
                        </span>
                        <!--摘要渲染-->
                        <span class="media-right">
                            {{ article.desc }}
                        </span>
                        <!--内容渲染-->
                        <span>
                            {{ article.content }}
                        </span>
                    </div>
                    <!-- 每个文章底部的标签，时间，评论，姓名等 -->
                    <div class="small pub_info">
                        <span><a href="">{{article.user.username}}</a></span> &nbsp;
                        <span>发布于:&nbsp;{{article.create_time|date:"Y-m-d H:i:s"}}</span>&nbsp;
                        <span class="glyphicon glyphicon-comment"></span>评论({{ article.comment_count }})&nbsp;
                        <span class="glyphicon glyphicon-thumbs-up"></span>点赞({{ article.up_count }})
                    </div>
                </div>
                <hr>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-3">
            <!--右侧主面板-->
            <div class="panel panel-primary">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
            <!--右侧默认面板-->
            <div class="panel panel-default">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>

        </div>
    </div>

</div>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/blog/bs/css/bootstrap.css">
</head>
<body>
<h3>登录页面</h3>
<div class="container">
    <div class="col-md-6 col-lg-offset-3">
        <form>
            {% csrf_token %}
            <div class="form-group">
                <label for="user">用户名</label>
                <input type="text" id="user" class="form-control">
            </div>

            <div class="form-group">
                <label for="pwd">密码</label>
                <input type="password" id="pwd" class="form-control">
            </div>

            <div class="form-group">
                <label for="pwd">验证码</label>
                <div class="row">
                    <div class="col-md-6">
                        <label>
                            <input type="text" class="form-control" id="valid_code">
                        </label>
                    </div>

                    <div class="col-md-6">
                        <img width="270" height="40" id="valid_code_img" src="/get_validCode_img/" alt="">
                    </div>
                </div>
            </div>
            <input type="button" class="btn btn-default login_btn" value="submit"><span class="error"></span>
            <a href="/register/" class="btn btn-success pull-right">注册</a>
        </form>
    </div>
</div>


<script src="/static/js/jquery-3.2.1.min.js"></script>
<script>
    // 刷新验证码
    $("#valid_code_img").click(function(){
        $(this)[0].src+="?"
    });

    //登陆验证
    $(".login_btn").click(function () {

        $.ajax({
            url:"",
            type:"post",
            data:{
                user:$("#user").val(),
                pwd:$("#pwd").val(),
                valid_code:$("#valid_code").val(),
                csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val(),
            },
            success:function (data) {
                console.log(data);
                if (data.user){
                    location.href = "/index/"
                }
                else{
                    $(".error").text(data.msg).css({"color":"red", "margin-left":"10px"})
                    // 一秒后清空报错信息
                    setTimeout(function () {

                        $(".error").text("")

                    },1000)
                }
            }
        })
    })



</script>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/blog/bs/css/bootstrap.css">
    <style>
        #avatar_img {
            margin-left: 20px
        }

        #avatar {
            display: None
        }
        .error{
            color: red;
        }
    </style>
</head>
<body>
<h3>注册页面</h3>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-lg-offset-3">
            <form id="form">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{field.auto_id}}">{{ field.label }}</label>
                        {{field}} <span class="error pull-right"></span>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <label for="avatar">
                        头像
                        <img id="avatar_img" width="60" height="60" src="/static/blog/img/default.png" alt="">
                    </label>
                    <input type="file" id="avatar">
                </div>

                <input type="button" class="btn btn-default reg_btn" value="submit" ><span class="error"></span>
            </form>
        </div>
    </div>
</div>

<script src="/static/js/jquery-3.2.1.min.js"></script>
<script>
    // 头像预览
    $("#avatar").change(function () {
        // 获取用户选中的文件对象
        var file_obj = $(this)[0].files[0];
        // 获取文件对象的路径
        var reader = new FileReader();
        reader.readAsDataURL(file_obj);
        // 修改img的src属性,src=文件对象的路径
        reader.onload = function () {
            $("#avatar_img").attr("src", reader.result)
        };
    });

    // Ajax提交数据
    $(".reg_btn").click(function () {

        // console.log($("#form").serializeArray());
        var formdata = new FormData();
        var request_data = $("#form").serializeArray();
        $.each(request_data,function (index, data) {
            formdata.append(data.name, data.value)
        });
        formdata.append("avatar", $("#avatar")[0].files[0]);


        // var formdata = new FormData();
        // formdata.append("user", $("#id_user").val());
        // formdata.append("pwd", $("#id_pwd").val());
        // formdata.append("re_pwd", $("#id_re_pwd").val());
        // formdata.append("email", $("#id_email").val());
        // formdata.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());
        // formdata.append("avatar", $("#avatar")[0].files[0]);


        $.ajax({
            url: "",
            type: "post",
            contentType: false,
            processData: false,
            data: formdata,
            success: function (data) {
                // console.log(data)
                if(data.user){
                    // 注册成功
                    // window.open("/login.html")
                    location.href="/login/"
                }
                else{
                    // 注册失败
                    // console.log(data.msg);
                    // 清空错误信息
                    $("span.error").html("");
                    $(".form-group").removeClass("has-error")
                    // 展示当前错误信息
                    $.each(data.msg, function (field, error_list) {
                        console.log(field, error_list);
                        if (field == "__all__"){
                            $("#id_re_pwd").next().html(error_list[0]).parent().addClass("has-error");
                        }

                        $("#id_" + field).next().html(error_list[0]);
                        // 找到父标签，框体变红提示error
                        $("#id_" + field).parent().addClass("has-error");
                    })
                }
            }
        })
    })
</script>

</body>
</html>